#!/bin/sh
set -e

if [ -n "${NGINX_GID}" ]; then
    groupmod --gid "${NGINX_GID}" --non-unique nginx
fi

if [ -n "${NGINX_UID}" ]; then
    usermod --non-unique --uid "${NGINX_UID}" nginx
fi

mkdir -p /run/nginx /var/cache/nginx

find /etc/nginx -type f -print0 | xargs -0 -I {} -n1 -- sh -c "dockerize -delims '⁅⁅:⁆⁆' -template '{}:{}' || exit 255"
