#!/bin/bash
set -e
shopt -s globstar

if [ -n "${NGINX_GID}" ]; then
    groupmod --gid "${NGINX_GID}" --non-unique nginx
fi

if [ -n "${NGINX_UID}" ]; then
    usermod --non-unique --uid "${NGINX_UID}" nginx
fi

mkdir -p /run/nginx /var/cache/nginx

for FILE in /etc/nginx/**/*; do
    dockerize -delims '⁅⁅:⁆⁆' -template "${FILE}":"${FILE}"
    dockerize -delims '\u2045\u2045:\u2046\u2046' -template "${FILE}":"${FILE}"
done
